### ISSUE TITLE
Would be nice to account for non-linear behavior introduced by elevator cord wrapping around the winch

### ISSUE THREAD

**Issue by jwalthour** [first95/FRC2020#1]
The number of encoder ticks required to lift the elevator by one inch changes depending how much elevator cord is wrapped around the winch.  We had assumed this would be a negligible amount, but it turns out the cord is about 1/8" diameter and the winch is only 1" diameter, so it can make a difference of a few percent.

**Comment by lindsayvallen** [comment]
That's fine, but I'm going to icebox it until we know if we'll have an elevator.

**Comment by lindsayvallen** [comment]
No elevator this year so removing this issue.
