### ISSUE TITLE
Modify drivebase for sucker chassis

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2020#11]
Should be done in feature branch. Will need to wait until design is sufficiently far along to know what the software spec should be.

**Comment by jwalthour** [comment]
I committed a draft of this functionality in f1581e66801b1903d826fa23084bc2aef4e40b6d, a branch named "feature/add_sucker".  I put it into the `DriveBase` subsystem for now; we should move it into its own subsystem if that ever becomes easier.

**Comment by jwalthour** [comment]
Sucker chassis outlawed

**Comment by lindsayvallen** [comment]
Since the season has gone in the crapper, we're looking at adding the sucker chassis despite the official ruling.

**Comment by lindsayvallen** [comment]
Merged develop into feature/add_sucker, and did some updating based on new info from JCH (re: one Talon only, ID 5, and don't use sucker when in high gear). Need to test it on robot once hardware is implemented.

**Comment by WesleyJ-128** [comment]
Sucker works, but is going to be removed for the 2021 season since it's unnecessary and still illegal.
