### ISSUE TITLE
Prepare bread bot for 2020

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2020#14]
Take existing breadboard, which is likely not fully functional at the moment, and prepare it for software testing. This should include:

- Swapping the SIM motor(s) for Neo motor(s)
- Swapping the Talon controller(s) for SparkMax controller(s)
- Adding any other components that are missing to get it running

**Comment by lindsayvallen** [comment]
This may be something where we want to leverage some non-software folks for assistance.

**Comment by jwalthour** [comment]
Additional tasks:
- [x] Upgrade firmware and image on roboRIO
- [x] Upgrade firmware on remaining talons, if any are left after upgrading to SparkMaxes
- [x] Upgrade firmware on SparkMax controllers, if an upgrade is available

**Comment by lindsayvallen** [comment]
The bread bot has a robo rio and mini-sims (drive pod) installed, along with a couple of Neos and their SparkMax controllers are in the process of being installed.

**Comment by zaaj** [comment]
Used RoboRIO imaging tool to Format Target with FRC_roboRIO_2020_v10.zip
and Update Firmware to check that Firmware version was already 6.0.0 - displayed as 6.0.0f1
Used Phoenix Tuner to update Talon SRX devices from 4.11 to 20.0

Still to do: update Spark MAX controllers

**Comment by zaaj** [comment]
Screenshots taken during the update
![Format Target with Image](https://user-images.githubusercontent.com/55641973/72397248-55189b80-370d-11ea-91dd-4be00d83e1e8.png)
![Run roboRIO Imaging Tool as Administrator](https://user-images.githubusercontent.com/55641973/72397249-55b13200-370d-11ea-98a4-78d3368e07ea.png)
![Update Firmware](https://user-images.githubusercontent.com/55641973/72397250-55b13200-370d-11ea-9912-84accb2445f8.png)
![Updating Talon SRX devices](https://user-images.githubusercontent.com/55641973/72397251-55b13200-370d-11ea-85b9-3c8c923ede7f.png)

**Comment by zaaj** [comment]
Followed the firmware update instructions at 
https://www.revrobotics.com/sparkmax-software/#firmware-update-instructions
and updated the firmware on the two Spark MAX's on the Bread Bot
![image](https://user-images.githubusercontent.com/55641973/72485845-12bb9100-37d7-11ea-9375-d3224a57fc22.png)
They were on version 1.4 - newer version includes the USB to CAN bus bridge, so I only needed to plug into the first one.  I set the CAN IDs to 31 and 32, but not sure that will stick after powering down

**Comment by zaaj** [comment]
Reviewed CAN connected devices on Bread Bot - checked Cross The Road Electronics website for any firmware updates available for the Pnumatics Control Module and the Power Distribution Panel - they were both on the most recent version available according to Phoenix Tuner

**Comment by zaaj** [comment]
Posting images to use in Firmware Update markdown here
![Set_REV_SparkMax_Client_to_runAsAdministrator](https://user-images.githubusercontent.com/55641973/72667331-d3648e80-39e8-11ea-86ec-b667abc6c92a.png)
