### ISSUE TITLE
Would be nice to have a way for the elevator "go to setpoint" command to exit into hold-position mode

### ISSUE THREAD

**Issue by jwalthour** [first95/FRC2020#2]
Right now, after completing automated ground loading of a hatch, the elevator drifts downward.  That's because in the cancel() function, stopElevator() is called.  This causes the elevator to stop holding position.

This was originally done as a fail-safe.  We probably want to either a) replace the cancel with a command to hold position, or b) give the command a way to have two difference cancellation behavior.

**Comment by lindsayvallen** [comment]
That's fine, but I'm going to icebox it until we know if we'll have an elevator.

**Comment by lindsayvallen** [comment]
We're not going to have an elevator so I'm closing this issue.
