### ISSUE TITLE
Evaluate possible vision hardware for this season

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2020#21]
Compare options and come up with what we should order.

**Comment by jwalthour** [comment]
I see the following avenues for computer vision:

1. [LimeLight](https://limelightvision.io/products/limelight-2-plus), for detection of port targets
    - This may also support control panel analysis depending on whether we can turn off the green light, and what kind of custom pipelines it'll accept from GRIP
2. Microsoft Lifecam 
    - With green ringlight, for detection of port targets (we already have this hardware in house)
    - With white ringlight, for control panel analysis [such as this one](https://www.amazon.com/Angel-Eyes-Halo-Ring-Angel-Eye/dp/B082V9H2KS/ref=sr_1_10?keywords=12v+ring+light&qid=1578758660&sr=8-10)
3. ["Knockoff BlackFly"](https://www.amazon.com/dp/B07MJFZK4S/ref=psdc_172511_t1_B07CSNC75T) plus one of the aforementioned ring lights
4. One of the above cameras, with an [RGB ring light](https://www.sparkfun.com/products/14965)
    - May require control via an [Arduino](https://www.sparkfun.com/products/11021)

I've asked Chris to order all the linked parts, for later evaluation.
