### ISSUE TITLE
manual power cell control request

### ISSUE THREAD

**Issue by jch13** [first95/FRC2020#36]
1 toggle button - deploy collector pneumatics, solenoid 1
1 momentary button - run collector at 0.7 talon #1, bonus roller at 0.8 talon #2, together
1 momentary button - run singulator at 0.8, talon #3
1 momentary button - run indexer at 0.7  spark max #10

**Comment by lindsayvallen** [comment]
Thanks @TairanJ @zaaj @NHDinosaur  for the team effort! I verified that all of these components run as requested manually, from one unified sub-system in develop.
