### ISSUE TITLE
Set it so the ground collector cannot run while retracted

### ISSUE THREAD

**Issue by NHDinosaur** [first95/FRC2020#37]
If the ground collector runs while retracted, it rubs against the intake for the singulator and causes damage. It would be good to add a limit so we don't have to make sure of this manually.

**Comment by zaaj** [comment]
How about:
`    if (deploy.get()) {
      Robot.powerCellMover.setRollerSpeed(Robot.oi.getGroundPickUpRollerAxis());
    } else {
      Robot.powerCellMover.setRollerSpeed(0);
    }`

**Comment by zaaj** [comment]
Oh, deploy is private at the moment.

**Comment by WesleyJ-128** [comment]
Did that, but inside ``setRollerSpeed()`` itself.
