### ISSUE TITLE
Add automated powercell handling using sensors

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2020#41]
This is the sensor logic from @jch13 

- 0 true, 3 false: run singulator
- 1 true, 3 false: stop singulator, start indexer
- 2 true, 3 false: stop indexer

**Comment by lindsayvallen** [comment]
Requires having issue #39 resolved before this is tested, but could write code before then.

**Comment by zaaj** [comment]
Created feature/Sensor_Based_Powercell_handling branch to work on this

**Comment by jwalthour** [comment]
THis is now working in develop
