### ISSUE TITLE
Decide how shooter should interact with PowerCellMover

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2020#42]
Right now shooter is a sub-system of its own. Need to decide if it should be integrated with PowerCellMover, in part because need to run indexer while shooting.

**Comment by lindsayvallen** [comment]
Should integrate shooter with rest of power cell handler.

**Comment by jwalthour** [comment]
Inputs:
- 2 user controls
    - Fire button
    - Intake button
- 4 sensors:
    - Singulator occupied (by 1 or more balls)
    - Indexer entrance occupied
    - Indexer position 1 occupied
    - Shooter loaded

Outputs:
- Speed of ground intake rollers
- Speed of singulator 
- Speed/position of indexer
- Speed of shooter flywheel

**Comment by jwalthour** [comment]
Whoops, I think I misread the scope of the issue - the above comment might not be quite right

**Comment by lindsayvallen** [comment]
Shooter has been integrated into power cell handler so closing this issue.
